#!/usr/bin/python3

import sys
import argparse
import random

parser = argparse.ArgumentParser(description='Chooses random name for your enjoyment')
parser.add_argument('-b','--boy', action='store_true', help='Random male name')
parser.add_argument('g','--girl', action='store_true', help='Random female name')

args = parser.parse_args()

if args.boy == True:
    # Read files and choose random
    f = open('male-names', 'r')
    data = f.read()
    print(random.choice(data.splitlines()))
elif args.girl == True:
    # Read files and choose random
    f = open('female-names', 'r')
    data = f.read()
    print(random.choice(data.splitlines()))

else:
    # Do boy
    print('Does this make me sexist?')
    f = open('male-names', 'r')
    data = f.read()
    print(random.choice(data.splitlines()))
